CREATE TABLE IF NOT EXISTS users
(
    user_id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_telegram_user_id      BIGINT,
    user_telegram_chat_id      BIGINT,
    user_telegram_name         VARCHAR,
    user_display_name          VARCHAR,
    user_state                 VARCHAR,
    user_share_contact_enabled BOOLEAN,
    user_profile_active        BOOLEAN
);

CREATE TABLE IF NOT EXISTS games
(
    game_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_name        VARCHAR,
    game_description VARCHAR
);